#
# This code is Copyright (C) <year> The Cambridge Crystallographic Data Centre
# (CCDC) of 12 Union Road, Cambridge CB2 1EZ, UK and a proprietary work of CCDC.
# This code may not be used, reproduced, translated, modified, disassembled or
# copied, except in accordance with a valid licence agreement with CCDC and may
# not be disclosed or redistributed in any form, either in whole or in part, to
# any third party. All copies of this code made in accordance with a valid
# licence agreement as referred to above must contain this copyright notice.
#
# No representations, warranties, or liabilities are expressed or implied in the
# supply of this code by CCDC, its servants or agents, except where such
# exclusion or limitation is prohibited, void or unenforceable under governing
# law.
#
- id: ccdc-copywrite-check
  name: CCDC Copywrite header check
  language: golang
  additional_dependencies:
    - github.com/hashicorp/copywrite@v1.1.3
  entry: main/hooks/copywrite_check.sh
  pass_filenames: false

- id: ccdc-copywrite-fix
  name: CCDC Copywrite header fix
  language: golang
  additional_dependencies:
    - github.com/hashicorp/copywrite@v1.1.3
  entry: main/hooks/copywrite_fix.sh
  pass_filenames: false
  stages: [manual]